### ISSUE TITLE
Each Time Save Button is pressed, the info file should be updated.

### ISSUE THREAD

**Issue by prabhjots** [prabhjots/SSImageNamer#2]

**Comment by prabhjots** [comment]
is it not happening already?

**Comment by sikhsiyasat** [comment]
No. It saves only First save.

**Comment by sikhsiyasat** [comment]
Top Priority

**Comment by prabhjots** [comment]
@sikhsiyasat I am not able to reproduce the issue. Are you making a change and then pressing save?

**Comment by prabhjots** [comment]
it was a miss understanding. user was trying command + s which is not implemented. they will need to press the save button.
